// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models;

public partial class CATEGORY
{
    public long id { get; set; }

    public string categoryName { get; set; }

    public string description { get; set; }

    public string remark { get; set; }

    public bool isActive { get; set; }

    public string imgUrl { get; set; }

    public virtual ICollection<PRODUCT> PRODUCT { get; set; } = new List<PRODUCT>();
}