// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models;

public partial class FILE
{
    public long id { get; set; }

    public string name { get; set; }

    public string tableName { get; set; }

    public string dataName { get; set; }

    public long? mainId { get; set; }

    public string descriptions { get; set; }

    public string option1 { get; set; }

    public int? option2 { get; set; }

    public string remark { get; set; }
}