// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models;

public partial class ORDER
{
    public long id { get; set; }

    public string name { get; set; }

    public string address { get; set; }

    public string remark { get; set; }

    public string phone { get; set; }

    public DateTime? timer { get; set; }

    public int? status { get; set; }

    public string note { get; set; }

    public string email { get; set; }
}