// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models;

public partial class ORDER_DETAILS
{
    public long id { get; set; }

    public string productName { get; set; }

    public double? price { get; set; }

    public int? quantity { get; set; }

    public string remark { get; set; }

    public string note { get; set; }

    public long? productId { get; set; }

    public long? orderId { get; set; }
}