// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models;

public partial class PRODUCT
{
    public long id { get; set; }

    public string productName { get; set; }

    public double? price { get; set; }

    public string imgUrl { get; set; }

    public string descriptions { get; set; }

    public long? categoryId { get; set; }

    public bool isActive { get; set; }

    public bool? isDelete { get; set; }

    public long? shopId { get; set; }

    public string test { get; set; }

    public virtual CATEGORY category { get; set; }
}