// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models;

public partial class PROFILE
{
    public long id { get; set; }

    public string name { get; set; }

    public string email { get; set; }

    public string phone { get; set; }
}