// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models;

public partial class SHOP
{
    public long id { get; set; }

    public string logoUrl { get; set; }

    public string shopName { get; set; }

    public string descriptions { get; set; }

    public string address { get; set; }

    public long? profileId { get; set; }
}