// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ecommerce.Models;

public partial class USER
{
    public long id { get; set; }

    public string userName { get; set; }

    public string passWord { get; set; }

    public int? type { get; set; }

    public long? profileId { get; set; }

    public string roleName { get; set; }
}